### ISSUE TITLE
Hooks - Padronizando a introdução

### ISSUE THREAD

**Issue by halian-vilela** [reactjs/pt-BR.reactjs.org#119]
Pessoal, bom dia!

Percebi que a introdução dos arquivos que falam sobre Hook é o mesmo texto em todos os arquivos:

> *Hooks* are a new addition in React 16.8. They let you use state and other React features without writing a class

Sendo assim, acho importante padronizarmos para evitar traduções diferentes em cada um dos arquivos.

Já vi algumas diferentes, então sugiro padronizarmos para a seguinte:

> *Hooks* são uma nova adição ao React 16.8. Eles permitem que você use o state e outros recursos do React sem escrever uma classe.

Se você traduziu ou ainda vai traduzir algum arquivo de Hooks, por favor atente-se sobre essa questão.

- - - - 

Listo abaixo os colaboradores que devem se atentar sobre isso:

  * [x] Introducing Hooks (@klzns) (#72)
  * [x] Hooks at a Glance (@gabrielbs) (#80)
  * [x] Using the State Hook (@vinicius98s) (#108)
  * [x] Using the Effect Hook (@WeslleyNasRocha) (#117)
  * [x] Rules of Hooks (@thadeu) (#11)
  * [x] Building Your Own Hooks (@WendellAdriel) (#78)
  * [x] Hooks API Reference (@thadeu) (#76)
  * [x] Hooks FAQ (@thefrontendwizard) (#115)

Obrigado.

**Comment by thefrontendwizard** [comment]
Arrumei na #115 👍

**Comment by WeslleyNasRocha** [comment]
arrumado na #117

**Comment by gabrielbs** [comment]
Boa iniciativa!
Na #80 já está assim

**Comment by vinicius98s** [comment]
#108 Ajustado!
