### ISSUE TITLE
Progresso de tradução do Blog

### ISSUE THREAD

**Issue by jhonmike** [reactjs/pt-BR.reactjs.org#151]
## Blog
_Priorizar ordem cronológica descendente - Vamos tentar não deixar gaps de um documento para o outro_

- [ ] 2020-09-22-introducing-the-new-jsx-transform.md (@jhonmike)
- [x] 2020-08-10-react-v17-rc.md (@DanielObara) (#448)
- [x] 2020-02-26-react-v16.13.0.md (@jussarasoares) (#405)
- [x] 2019-11-06-building-great-user-experiences-with-concurrent-mode-and-suspense.md (@juliano-nunes) (#390)
- [x] 2019-10-22-react-release-channels.md (@juliano-nunes) (#397)
- [x] 2019-08-15-new-react-devtools.md (@brunodahora) (#331)
- [x] 2019-08-08-react-v16.9.0.md (@jhonmike) (#317)
- [x] 2019-02-23-is-react-translated-yet.md (@Luanf) (#155)
- [x] 2019-02-06-react-v16.8.0.md (@CaiqueMOliveira) (#162)
- [x] 2018-12-19-react-v-16-7.md (@jhonmike) (#156)
- [x] 2018-11-27-react-16-roadmap.md (@jlucfarias) (#171) 
- [x] 2018-11-13-react-conf-recap.md (@DanielObara) (#165)
- [x] 2018-10-23-react-v-16-6.md (@DanielObara) (#179)
- [x] 2018-10-01-create-react-app-v2.md (@felipemfp) (#166)
- [x] 2018-09-10-introducing-the-react-profiler.md (@brunodahora) (#336)
- [x] 2018-08-01-react-v-16-4-2.md (@gstvribs) (#177)
- [x] 2018-06-07-you-probably-dont-need-derived-state.md (@Luanf) (#183)
- [x] 2018-05-23-react-v-16-4.md (@reebr) (#181)
- [x] 2018-03-29-react-v-16-3.md (@thalees) (#210)
- [x] 2018-03-27-update-on-async-rendering.md (@rn4n) (#208)
- [x] 2018-03-01-sneak-peek-beyond-react-16.md (@Luanf) (#190)
- [ ] 2017-12-15-improving-the-repository-infrastructure.md (@gstvribs, @FelipeAlvesSilva) (#197)
- [x] 2017-12-07-introducing-the-react-rfc-process.md (@netochaves) (#189)
- [x] 2017-11-28-react-v16.2.0-fragment-support.md (@CaiqueMOliveira) (#187)
- [x] 2017-09-26-react-v16.0.md (@lucianomlima) (#349)
- [x] 2017-09-25-react-v15.6.2.md (@netochaves) (#200)
- [ ] 2017-09-08-dom-attributes-in-react-16.md (@lucaspolizeli) (#198)
- [x] 2017-07-26-error-handling-in-react-16.md (@CaiqueMOliveira) (#201)
- [x] 2017-06-13-react-v15.6.0.md (@thalees) (#203)
- [x] 2017-05-18-whats-new-in-create-react-app.md (@matheuspiment) (#294)
- [x] 2017-04-07-react-v15.5.0.md (@felipe-michelon) (#209)
- [x] 2016-11-16-react-v15.4.0.md (@FelipeAlvesSilva) (#426)
- [x] 2016-09-28-our-first-50000-stars.md (@tota1099) (#242)
- [x] 2016-08-05-relay-state-of-the-state.md (@ricardovasconcelos) (#436)
- [x] 2016-07-22-create-apps-with-no-configuration.md (@gustafsilva) (#202)
- [x] 2016-07-13-mixins-considered-harmful.md (@DanielObara) (#425)
- [x] 2016-07-11-introducing-reacts-error-code-system.md (@tavareshenrique) (#427)
- [x] 2016-04-08-react-v15.0.1.md (@gustafsilva) (#379)
- [x] 2016-04-07-react-v15.md (@elderferreiras) (#355)
- [x] 2016-03-29-react-v0.14.8.md (@jussarasoares) (#343)
- [x] 2016-03-16-react-v15-rc2.md (@jhonmike) (#344)
- [x] 2016-03-07-react-v15-rc1.md (@rn4n) (#347)
- [x] 2016-02-19-new-versioning-scheme.md (@islanrodrigues) (#364)
- [x] 2016-01-12-discontinuing-ie8-support.md (@mjr) (#352)
- [x] 2016-01-08-A-implies-B-does-not-imply-B-implies-A.md (@mdapper) (#353)

Pessoal os posts antes de 2016, não vou listar para traduzirmos, mas caso alguém encontre um post que ache importante traduzir pode comentar aqui ou apenas abrir um PR com a tradução

**Comment by Luanf** [comment]
Boa! Posso pegar o mais recente? (is-react-translated-yet)
é bom traduzirmos em ordem cronológica reversa

**Comment by glaucia86** [comment]
Divulgando essa issue no twitter e linkedin para atrair mais ajuda da Comunidade Técnica! 
Obrigada @jhonmike :)

**Comment by Luanf** [comment]
Aberto PR rascunho com um pouco mais da metade do primeiro item da lista traduzido.
Termino assim que der :pray: 
(#155)

**Comment by CaiqueMOliveira** [comment]
PR aberto para a página "**The One With Hooks**" (#162). 
Por favor, caso encontrem algo a ser melhorado, não existem em me avisar. ;)

**Comment by leonascimento** [comment]
@jhonmike  
Eu vou traduzir o [2018-09-10-introducing-the-react-profiler.md](https://github.com/reactjs/pt-BR.reactjs.org/blob/master/content/blog/2018-09-10-introducing-the-react-profiler.md) tá ok?

**Comment by John-Luke** [comment]
@jhonmike Pode me dar o `2018-11-27-react-16-roadmap.md`?

**Comment by DanielObara** [comment]
@jhonmike posso contribuir com o  2018-11-13-react-conf-recap.md?

**Comment by felipemfp** [comment]
@jhonmike,

Posso contribuir com o `2018-10-01-create-react-app-v2.md`?

**Comment by halian-vilela** [comment]
Pessoal que for chegando para traduzir, tentem manter a ordem cronológica inversa para não deixar gaps.

O próximo que puder, dar preferência para `2018-10-23-react-v-16-6.md` antes de continuar descendo.

**Comment by DanielObara** [comment]
Passa pra mim essa, 2018-10-23-react-v-16-6.md.

**Comment by gstvribs** [comment]
Posso ajudar com 2018-08-01-react-v-16-4-2.md

**Comment by crisgon** [comment]
Posso ajudar com a `2018-03-27-update-on-async-rendering.md`

**Comment by halian-vilela** [comment]
> Posso ajudar com 2018-08-01-react-v-16-4-2.md

Ok! Atribuído!

**Comment by halian-vilela** [comment]
> Posso ajudar com a `2018-03-27-update-on-async-rendering.md`

@crisgon 

Vc se importaria de traduzir `2018-06-07-you-probably-dont-need-derived-state.md` em vez do que sugeriu? 

Creio que seria importante mantermos a ordem para não deixar gaps entre os documentos.

O que acha?

**Comment by Luanf** [comment]
Semana complicadinha mas consegui subir o que faltava do #155 agora pouco.
Aceitando reviews! Vou tentar fazer algumas revisões de outros PR's durante o fim de semana, também.

Podem me passar a próxima issue a ser traduzida? talvez `2018-06-07-you-probably-dont-need-derived-state.md` se o @crisgon não se manifestar ou então a seguinte (`2018-05-23-react-v-16-4.md`)

**Comment by reebr** [comment]
Gostaria de realizar a tradução do `2018-03-29-react-v-16-3.md` visto que os dois anteriores aparentemente já possui interessados:
- `2018-06-07-you-probably-dont-need-derived-state.md`: @crisgon 
- `2018-05-23-react-v-16-4.md`: @Luanf

**Comment by jhonmike** [comment]
@Luanf como o @crisgon não se manifestou ainda, vou te adicionar na sequência, e @reebr também ficara assim: 

```
- [ ] 2018-06-07-you-probably-dont-need-derived-state.md @Luanf 
- [ ] 2018-05-23-react-v-16-4.md @reebr 
```

caso já tenham começado a tradução me avisem que eu mudo.

**Comment by DanielObara** [comment]
Pessoal estou tendo problemas para conseguir apagar com o backspace os conteúdos de dentro dos arquivos .md. Consigo deletar apenas com o delete, alguém tem alguma ideia do que possa ser?

**Comment by WendellAdriel** [comment]
@DanielObara se estiver usando o VS Code, verifique no canto inferior direito se o arquivo está associado corretamente à extensão markdown, se estiver, pode ser conflito de extensão, mas comigo tinha acontecido algo assim e por algum motivo, meu VS Code tinha deixado de associar os arquivos md com a extensão Markdown e estava gerando erros

**Comment by DanielObara** [comment]
@WendellAdriel está 

> @DanielObara se estiver usando o VS Code, verifique no canto inferior direito se o arquivo está associado corretamente à extensão markdown, se estiver, pode ser conflito de extensão, mas comigo tinha acontecido algo assim e por algum motivo, meu VS Code tinha deixado de associar os arquivos md com a extensão Markdown e estava gerando erros

@WendellAdriel  está referenciado sim.. acho que na verdade o que acontece é algum delay muito ferrado que demora uns 15 seg pra deletar... e não é só no meu pc, em outros tbm.

**Comment by DanielObara** [comment]
> @DanielObara se estiver usando o VS Code, verifique no canto inferior direito se o arquivo está associado corretamente à extensão markdown, se estiver, pode ser conflito de extensão, mas comigo tinha acontecido algo assim e por algum motivo, meu VS Code tinha deixado de associar os arquivos md com a extensão Markdown e estava gerando erros


@WendellAdriel  está referenciado sim, acontece é que ocorre um delay ferrado de uns 10 seg pra apagar após o comando do backspace. Já testei em outro pc e ocorre a mesma coisa.

**Comment by DanielObara** [comment]
Efetuado PR #179

**Comment by MizaelMelo** [comment]
Fala, galera! Posso pegar o '2018-03-29-react-v-16-3.md' para traduzir?

**Comment by felipemfp** [comment]
Posso pegar o `2018-03-27-update-on-async-rendering.md`?

**Comment by Luanf** [comment]
PR do `2018-06-07-you-probably-dont-need-derived-state.md` aberto: #183
Me passa o `2018-03-01-sneak-peek-beyond-react-16.md` fazendo favor? :smile:

**Comment by gstvribs** [comment]
Pessoal, alguém consegue me passar o `2017-12-15-improving-the-repository-infrastructure.md` ?

**Comment by netochaves** [comment]
@jhonmike pode me passar o 2017-12-07-introducing-the-react-rfc-process.md ?

**Comment by halian-vilela** [comment]
@netochaves 

Tá lá! Qdo abrir a PR nos avise! Valeu!

**Comment by CaiqueMOliveira** [comment]
Hey guys!!

I'd like to translate the `2017-11-28-react-v16.2.0-fragment-support.md`.
Could anyone assign me please  ;)

**Comment by netochaves** [comment]
PR efetuada #189

**Comment by Luanf** [comment]
Aceito o próximo! :pray:

**Comment by netochaves** [comment]
Posso assumir o ` 2017-09-25-react-v15.6.2.md`?

**Comment by CaiqueMOliveira** [comment]
PR disponível para revisões **Translation of Fragment Support** (#187) :v:

**Comment by lucaspolizeli** [comment]
Fala galera!
Posso contribuir com o `2017-09-08-dom-attributes-in-react-16.md`?

**Comment by jhonmike** [comment]
@leonascimento, @MizaelMelo e @felipemfp faz mais de 15 dias que fizeram os pedidos, se precisar de ajuda ou quiserem liberar os posts para outras pessoas traduzirem, avisem fazendo favor!! :)

**Comment by CaiqueMOliveira** [comment]
Boa noite galera!!
Poderiam me atribuir a página `2017-07-26-error-handling-in-react-16.md` por favor?

**Comment by thalees** [comment]
Boa noite pessoal ! 
Posso assumir a página `2017-06-13-react-v15.6.0.md` ? 😄

**Comment by filipenatanael** [comment]
Boa noite Pessoal, Tudo bem?
Posso assumir a página `2017-05-18-whats-new-in-create-react-app.md` ?

**Comment by FMichelon** [comment]
Boa noite!
Posso pegar a página `2017-04-07-react-v15.5.0.md` ?

**Comment by felipe-michelon** [comment]
Boa noite!
Posso pegar a página 2017-04-07-react-v15.5.0.md ?

**Comment by netochaves** [comment]
PR efetuada, toda revisão é bem vinda. #200

**Comment by gustafsilva** [comment]
Posso ajudar com o post `2016-07-22-create-apps-with-no-configuration.md`?

**Comment by jhonmike** [comment]
@gustafsilva  o ideal é seguir a ordem, mas como já abriu o PR não vamos barrar por esse motivo haha
mas fica a dica para a proxima :D

> _Priorizar ordem cronológica descendente - Vamos tentar não deixar gaps de um documento para o outro_

**Comment by gustafsilva** [comment]
@jhonmike o próximo seria o ` 2016-11-16-react-v15.4.0.md`?

**Comment by jhonmike** [comment]
Pessoal que quiser pegar algum post, liberei os seguintes post:
- 2018-09-10-introducing-the-react-profiler.md
- 2018-03-29-react-v-16-3.md
- 2018-03-27-update-on-async-rendering.md

Porque já faz mais de 25 dias que estão aguardando seus PRs!!

caso o pessoal que tinha pedido eles voltem a querer contribuir é só pegar o que tiver na sequência que atribuo novamente :D

**Comment by netochaves** [comment]
posso assumir o `2018-09-10-introducing-the-react-profiler.md`

**Comment by thalees** [comment]
> Pessoal que quiser pegar algum post, liberei os seguintes post:
> 
> * 2018-09-10-introducing-the-react-profiler.md
> * 2018-03-29-react-v-16-3.md
> * 2018-03-27-update-on-async-rendering.md
> 
> Porque já faz mais de 25 dias que estão aguardando seus PRs!!
> 
> caso o pessoal que tinha pedido eles voltem a querer contribuir é só pegar o que tiver na sequência que atribuo novamente :D

Eu posso pegar o ` 2018-03-29-react-v-16-3.md` se puder :smile:

**Comment by reebr** [comment]
Posso iniciar a tradução do `2018-03-27-update-on-async-rendering.md`?

**Comment by tota1099** [comment]
Posso iniciar a tradução do 2016-09-28-our-first-50000-stars?

**Comment by gustafsilva** [comment]
Posso assumir o `2016-08-05-relay-state-of-the-state.md`?

**Comment by IagoAugusto** [comment]
Posso iniciar a tradução do  2016-08-05-relay-state-of-the-state.md?

**Comment by igorjm** [comment]
Boa tarde pessoal,

Ainda estão realizando o processo de tradução do blog?

Se sim, eu poderia iniciar a tradução 2016-07-13-mixins-considered-harmful.md?

**Comment by jhonmike** [comment]
atribuído a tradução a você @igorjm

**Comment by gamoridev** [comment]
Fala, galera.

Posso iniciar a tradução do **2016-07-11-introducing-reacts-error-code-system.md**.

**Comment by jhonmike** [comment]
@gamoridev atribuído :metal:

**Comment by jhonmike** [comment]
## Bom dia pessoal

### Posso liberar os posts listados abaixo para que outras pessoas possam assumir a tradução deles, pois, ainda não foram iniciados e já esta na lista a algum tempo:

2018-09-10-introducing-the-react-profiler.md (@netochaves) [NO PULL-REQUEST YET]
2017-09-26-react-v16.0.md (@Luanf) [NO PULL-REQUEST YET]
2017-05-18-whats-new-in-create-react-app.md (@filipenatanael) [NO PULL-REQUEST YET]
2016-11-16-react-v15.4.0.md (@gustafsilva) [NO PULL-REQUEST YET]
2016-08-05-relay-state-of-the-state.md (@IagoAugusto) [NO PULL-REQUEST YET]

### Também temos alguns PRs em aberto se alguém estiver precisando de ajuda só avisar:

2018-11-27-react-16-roadmap.md (@John-Luke) (#171)
2018-03-27-update-on-async-rendering.md (@reebr) (#208)
2017-12-15-improving-the-repository-infrastructure.md (@gstvribs) (#197)
2017-09-08-dom-attributes-in-react-16.md (@lucaspolizeli) (#198)

**Comment by reebr** [comment]
@jhonmike eu acabei esquecendo, vou dar continuidade na tradução. 😃

**Comment by aranhaagency** [comment]
Gostaria de ficar com esse post 2018-09-10-introducing-the-react-profiler.md (@netochaves) [NO PULL-REQUEST YET]

**Comment by lucaspolizeli** [comment]
> ## Bom dia pessoal
> ### Posso liberar os posts listados abaixo para que outras pessoas possam assumir a tradução deles, pois, ainda não foram iniciados e já esta na lista a algum tempo:
> 2018-09-10-introducing-the-react-profiler.md (@netochaves) to: @aranhaagency [Resolvido](https://github.com/reactjs/pt-BR.reactjs.org/issues/151#issuecomment-506986637)
> 2017-09-26-react-v16.0.md (@Luanf) [NO PULL-REQUEST YET]
> 2017-05-18-whats-new-in-create-react-app.md (@filipenatanael) [NO PULL-REQUEST YET]
> 2016-11-16-react-v15.4.0.md (@gustafsilva) [NO PULL-REQUEST YET]
> 2016-08-05-relay-state-of-the-state.md (@IagoAugusto) [NO PULL-REQUEST YET]
> 
> ### Também temos alguns PRs em aberto se alguém estiver precisando de ajuda só avisar:
> 2018-11-27-react-16-roadmap.md (@John-Luke) (#171)
> 2018-03-27-update-on-async-rendering.md (@reebr) (#208) [Resolvido no comentário abaixo](https://github.com/reactjs/pt-BR.reactjs.org/issues/151#issuecomment-505890873)
> 2017-12-15-improving-the-repository-infrastructure.md (@gstvribs) (#197)
> 2017-09-08-dom-attributes-in-react-16.md (@lucaspolizeli) (#198)

Tinha esquecido, mas vou finalizar!

**Comment by gstvribs** [comment]
Também tinha esquecido @jhonmike, irei continuá-lo, como é um MD bem grande se alguém puder ajudar também, agradeço : )

**Comment by marcospedro97** [comment]
@gstvribs se precisar de ajuda me dá um toque que eu aceito

**Comment by jhonmike** [comment]
## Bom dia pessoal

### Como [comentado acima](https://github.com/reactjs/pt-BR.reactjs.org/issues/151#issuecomment-505842666) estou liberando os seguintes posts por falta de retorno:

```
2017-09-26-react-v16.0.md
2017-05-18-whats-new-in-create-react-app.md
2016-11-16-react-v15.4.0.md
2016-08-05-relay-state-of-the-state.md
```

**Comment by jcserracampos** [comment]
Pessoal,
Sugiro transformar esta issue em um projeto.
Eu criei um board https://github.com/reactjs/pt-BR.reactjs.org/projects/1
A ideia é que cada artigo vire uma issue e que controlemos o andamento pelo Kanban.
Ficaria bem mais fácil de acompanhar.

**Comment by jhonmike** [comment]
Esta funcionando bem aqui na issue, e temos todo o histórico, mas se quiser controlar pelo board tranquilo!

**Comment by jcserracampos** [comment]
@jhonmike Eu estou pensando no tamanho da issue com o tempo. Acredito que fique ruim para gerenciar ao longo prazo.
Como cada artigo viraria uma issue, teríamos um processo definido de tradução com começo, meio e fim.

**Comment by jhonmike** [comment]
sim sim, vou tentar ajudar na criação das issues com os posts que ainda não tem ninguém traduzindo ;)

**Comment by andrescalco** [comment]
Vi que `2016-11-16-react-v15.4.0.md` está disponível para tradução. Posso pegar?

**Comment by jhonmike** [comment]
@andrescalco pode pegar ela sim, é esta issue aqui: https://github.com/reactjs/pt-BR.reactjs.org/issues/281

**Comment by elderferreiras** [comment]
Posso pegar 2016-04-07-react-v15.md?

**Comment by jhonmike** [comment]
@elderferreirasd pode pegar, se quiser também tem alguns posts mais novos para traduzir, como:

- 2017-05-18-whats-new-in-create-react-app.md
- 2016-04-08-react-v15.0.1.md

qualquer coisa me avisa que altero!! mas se quiser pode traduzir esse mesmo que vc comentou sem problemas ;)

**Comment by gustafsilva** [comment]
Posso pegar o `2017-05-18-whats-new-in-create-react-app.md`? :smile:

**Comment by jhonmike** [comment]
Boa @gustafsilva, pode mandar ver!!

**Comment by gustafsilva** [comment]
Pode sim @jhonmike :+1:

**Comment by jussarasoares** [comment]
Vou traduzir o post `2016-03-29-react-v0.14.8.md` 😉

**Comment by reebr** [comment]
Vou pegar o `2016-03-07-react-v15-rc1.md`, ok @jhonmike ? 😸

**Comment by islanrodrigues** [comment]
Olá, @jhonmike 
Adoraria em fazer parte da contribuição aqui. 
Poderia me passar o `2016-02-19-new-versioning-scheme.md`?

**Comment by islanrodrigues** [comment]
Olá, @jhonmike 
Adoraria fazer parte da contribuição aqui. 
Poderia me passar o `2016-02-19-new-versioning-scheme.md`?

**Comment by jhonmike** [comment]
concerteza @islanrodrigues , esta atribuído a sua pessoal hehe!!

**Comment by lucianomlima** [comment]
Abri um PR para a 2017-09-26-react-v16.0: https://github.com/reactjs/pt-BR.reactjs.org/pull/349

**Comment by mjr** [comment]
Abri um PR para o post `2016-01-12-discontinuing-ie8-support.md`: #352

**Comment by mdapper** [comment]
Estou trabalhando na tradução do `2016-01-08-A-implies-B-does-not-imply-B-implies-A.md`. Em breve abro a PR.

**Comment by jhonmike** [comment]
@mjr e @mdapper só vou deixar como dica para as próximas contribuições, antes de começar a traduzir alguma page ou post do blog, avisar de alguma forma, ou criar uma issue caso não tenha uma já criada, evitando que alguém traduza o mesmo documento que vcs!

**Comment by mjr** [comment]
Posso traduzir essa aqui também: 2016-07-11-introducing-reacts-error-code-system.md, vi que está atribuída para @gamoridev, mas me parece que ele ainda não pode fazer.

**Comment by mdapper** [comment]
@jhonmike obrigado pela dica, na verdade havia avisado aqui primeiro e comecei a traduzir. Como o post era curto acabei antes de alguém dar o OK e mandei logo a PR. Da próxima vez vou abrir a Issue primeiro :sweat_smile:

**Comment by jhonmike** [comment]
tranquilo @mdapper,  @mjr era bom confirmar antes com o @gamoridev !

mas tem outros posts, mais antigos que não estão nessa lista, que podem ser traduzidos, só não estão listados porque hoje já não tem tanta relevância!

**Comment by mjr** [comment]
@jhonmike essa parte [Introducing Concurrent Mode (Experimental)](https://reactjs.org/docs/concurrent-mode-patterns.html) vai está disponível para tradução?

**Comment by jhonmike** [comment]
Sim, o bot já enviou, logo vou adicionar as paginas novas!

**Comment by gamoridev** [comment]
Fala, galera. Não tive tempo de realizar a tradução para `2016-07-11-introducing-reacts-error-code-system.md`. Quem puder e quiser pegar para adiantar, fique a vontade! (@mjr )

**Comment by islanrodrigues** [comment]
PR aberto para `2016-02-19-new-versioning-scheme.md`: #364

**Comment by jhonmike** [comment]
Galera foi adicionado no topo da lista os últimos posts inseridos pelo bot nos PRs #362 e #365

**Comment by guilhermepiovesan** [comment]
@jhonmike posso traduzir o post `2019-10-22-react-release-channels.md`?

**Comment by elderferreiras** [comment]
Posso pegar `2019-11-06-building-great-user-experiences-with-concurrent-mode-and-suspense.md`?

**Comment by lcnogueira** [comment]
@jhonmike , pelo que entendi, todas as páginas da lista já estão em processo ou atribuídas para tradução. No caso, à medida que novas páginas são adicionadas ao blog, você vai liberando aqui, é isso?

**Comment by jhonmike** [comment]
isso @lcnogueira na real tem alguns posts aqui que o pessoal reservou mais não fez e já faz alguns meses que esta parado, então assim que der eu ou alguém da comu precisa fazer uma curadoria rápida do status dos posts e atualizar esses cara ai encima.

Outro ponto é que tem posts mais antigos que esses que não estão na lista e vc pode traduzir também, eu não deixei eles na lista porque achei q o valor em traduzi-los não era tao grande, mas se quiser pegar algum fique a vontade 🤘 , você pode encontrados aqui https://github.com/reactjs/pt-BR.reactjs.org/tree/master/content/blog todos que estão abaixo do ano de 2016 não estão listados aqui!

**Comment by lcnogueira** [comment]
Entendi, @jhonmike . Realmente, olhando aqui os de 2016, não sei se traria valor. Acho melhor ficar acompanhando e, quando abrir novas páginas, pegar uma mais recente para ajudar. Vou ficar acompahando. Vlw :metal: .

**Comment by jhonmike** [comment]
@guilhermepiovesan e @elderferreiras precisam de ajuda para traduzir os posts? esses posts são os mais recentes seria legal conseguirmos liberar eles em pt-br!

**Comment by elderferreiras** [comment]
@jhonmike voce pode liberar o post que peguei. Os ultimos dias de 2019 foram corridos e acabei nao comecando a fazer a traducao.

**Comment by juliano-nunes** [comment]
@jhonmike posso fazer esse post que o @elderferreiras liberou

**Comment by jhonmike** [comment]
tranquilo @elderferreiras tamo junto 🤘

pode sim @juliano-nunes 🚀

**Comment by juliano-nunes** [comment]
@jhonmike se o @guilhermepiovesan liberar, posso pegar o blog `2019-10-22-react-release-channels.md`

**Comment by jhonmike** [comment]
@juliano-nunes se tiver com tempo pode mandar bala, acho que o @guilhermepiovesan não vai responder e esse é um dos últimos post, acho valida traduzirmos!

**Comment by guilhermepiovesan** [comment]
@jhonmike desculpe a ausência, tá liberado @juliano-nunes!

**Comment by jhonmike** [comment]
tranquilo @guilhermepiovesan tamo junto 🤘

**Comment by juliano-nunes** [comment]
@jhonmike aberto o PR #397

**Comment by jussarasoares** [comment]
posso traduzir 2020-02-26-react-v16.13.0.md  ?

**Comment by DanielObara** [comment]
Vou pegar o mixins-considered-harmful.md !

**Comment by FelipeAlvesSilva** [comment]
Poderia dar realizar PR para a tradução **2016-11-16-react-v15.4.0.md**?

**Comment by jhonmike** [comment]
@andrescalco vou repassar a tradução para o @FelipeAlvesSilva, ok?

**Comment by jhonmike** [comment]
@FelipeAlvesSilva como não tivemos retorno pode iniciar a tradução, vou transferir para o seu nome no comentário inicial da issue.

**Comment by tavareshenrique** [comment]
A **2016-07-11-introducing-reacts-error-code-system.md** está livre? Se sim, gostaria de estar ajudando, por favor.

**Comment by jhonmike** [comment]
@GabrielAmazonas vou repassar a tradução para o @tavareshenrique, ok?

**Comment by FelipeAlvesSilva** [comment]
@jhonmike Aberta PR #426

**Comment by jhonmike** [comment]
@tavareshenrique pode assumir a tradução, já que não tivemos respostas

**Comment by FelipeAlvesSilva** [comment]
** 2017-12-15-improving-the-repository-infrastructure.md** está livre? Caso esteja ou algum outro post esteja gostaria de contribuir.

**Comment by jhonmike** [comment]
@FelipeAlvesSilva tem um PR aberto com o começo da tradução, se puder comentar lá PR #197, esse PR é do @gstvribs se ele não for dar continuidade, pode seguir que marco aqui

**Comment by DanielObara** [comment]
@jhonmike se for colocar o post sobre [Release Candidate React 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html) gostaria de pegar para traduzir pois já estou trabalhando em uma tradução para um post.

Valeu!

**Comment by jhonmike** [comment]
heheh ok @DanielObara assim que o bot enviar as alterações te marco no PR 🚀

**Comment by jhonmike** [comment]
@DanielObara o post já esta diponivel para tradução >> https://github.com/reactjs/pt-BR.reactjs.org/blob/master/content/blog/2020-08-10-react-v17-rc.md

**Comment by DanielObara** [comment]
Eu estava vendo no glossário onde temos alguns exemplos de palavras a serem evitadas a tradução. Uma delas é release, acha que ficaria melhor mesmo deixar por exemplo 

> "Hoje, estamos publicando o primeiro candidato à release do React 17"
ao invés de:
> "Hoje, estamos publicando o primeiro candidato à lançamento do React 17"

**Comment by DanielObara** [comment]
Galera, uma pergunta, como vocês traduziriam o termo 'lazy-load'? Carregamento lento?

**Comment by elderferreiras** [comment]
@DanielObara Por ser um design pattern, eu diria que o certo seria nao traduzir `lazy-load`. Ate [na pagina da Wikipedia ](https://pt.wikipedia.org/wiki/Lazy_loading)o termo nao aparece em portugues.

**Comment by DanielObara** [comment]
Pois é man eu achei que talvez ficasse realmente estranho traduzir lazy-load porém no glossario de tradução não consta essa palavra lá. vou adicionar depois

**Comment by jhonmike** [comment]
Pessoal irei fechar a issue e assim que tiver mais novidades sobre a reestruturação da doc do React abrimos uma nova issue organizando as novas traduções, obrigado a todos que participaram do processo de tradução do blog do React 👏👏👏 🏆
