### ISSUE TITLE
[New] Tradução Concurrent Mode e Release Channels

### ISSUE THREAD

**Issue by jhonmike** [reactjs/pt-BR.reactjs.org#356]
### Novas páginas que foram adicionadas  na sincronização #351:

- [x] content/docs/concurrent-mode-adoption.md (@juliano-nune) (#376)
- [x] content/docs/concurrent-mode-intro.md (@jhonmike) (#357) 
- [x] content/docs/concurrent-mode-patterns.md (@mdapper) (#360)
- [x] content/docs/concurrent-mode-reference.md (@guilhermepiovesan) (#368)
- [x] content/docs/concurrent-mode-suspense.md (@mjr) (#358)
- [x] content/docs/release-channels.md (@guilhermepiovesan) (#367)

Comente abaixo qual doc gostaria de traduzir que irei reserva-la.

**Comment by jhonmike** [comment]
@mjr só dizer qual _page_ você quer iniciar a tradução que marco aqui hehe!

**Comment by mjr** [comment]
Vou traduzir essa `concurrent-mode-suspense`.

**Comment by mdapper** [comment]
Abri uma PR em WIP da tradução da página acima. https://github.com/reactjs/pt-BR.reactjs.org/pull/360

**Comment by juliano-nunes** [comment]
Gostaria de pegar a `concurrent-mode-adoption`

**Comment by guilhermepiovesan** [comment]
@jhonmike posso pegar a página `content/docs/release-channels.md`?

**Comment by jhonmike** [comment]
pode mandar ver @guilhermepiovesan

**Comment by jhonmike** [comment]
Galera na última sincronização do bot (https://github.com/reactjs/pt-BR.reactjs.org/pull/365/) veio algumas alterações nas docs que estamos traduzindo, estou pensando em dar merge nas pages que foram alteradas, mas os PRs que já fizemos precisaremos tratar os conflitos e garantir que nossas traduções estarão alinhadas com as alterações!

Estou escrevendo aqui, porque na maioria dos casos foi relacionado as pages dessa issue.

**Comment by guilhermepiovesan** [comment]
Tradução do `content/docs/release-channels.md` foi criada no PR #367

**Comment by guilhermepiovesan** [comment]
@jhonmike eu poderia traduzir também o `content/docs/concurrent-mode-reference.md`?

**Comment by jhonmike** [comment]
Show @guilhermepiovesan, vou anotar aqui! 👏

**Comment by guilhermepiovesan** [comment]
Tradução do `content/docs/concurrent-mode-reference.md` criada no PR #368

**Comment by felipeemarcon** [comment]
Alguma ainda disponível?

**Comment by jhonmike** [comment]
@felipeemarcon no momento apenas os posts do blog do react, da uma olhada nesta issue > https://github.com/reactjs/pt-BR.reactjs.org/issues/151

**Comment by juliano-nunes** [comment]
@jhonmike abri o PR #376

**Comment by jhonmike** [comment]
Done!
